# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sage/audio2face/proto/audio2face.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&sage/audio2face/proto/audio2face.proto\x12\x11nvidia.audio2face\"{\n\x10PushAudioRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x12\n\nsamplerate\x18\x02 \x01(\x05\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\x12(\n block_until_playback_is_finished\x18\x04 \x01(\x08\"5\n\x11PushAudioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x85\x01\n\x16PushAudioStreamRequest\x12@\n\x0cstart_marker\x18\x01 \x01(\x0b\x32(.nvidia.audio2face.PushAudioRequestStartH\x00\x12\x14\n\naudio_data\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"l\n\x15PushAudioRequestStart\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x12\n\nsamplerate\x18\x02 \x01(\x05\x12(\n block_until_playback_is_finished\x18\x03 \x01(\x08\";\n\x17PushAudioStreamResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd4\x01\n\nAudio2Face\x12X\n\tPushAudio\x12#.nvidia.audio2face.PushAudioRequest\x1a$.nvidia.audio2face.PushAudioResponse\"\x00\x12l\n\x0fPushAudioStream\x12).nvidia.audio2face.PushAudioStreamRequest\x1a*.nvidia.audio2face.PushAudioStreamResponse\"\x00(\x01\x62\x06proto3')



_PUSHAUDIOREQUEST = DESCRIPTOR.message_types_by_name['PushAudioRequest']
_PUSHAUDIORESPONSE = DESCRIPTOR.message_types_by_name['PushAudioResponse']
_PUSHAUDIOSTREAMREQUEST = DESCRIPTOR.message_types_by_name['PushAudioStreamRequest']
_PUSHAUDIOREQUESTSTART = DESCRIPTOR.message_types_by_name['PushAudioRequestStart']
_PUSHAUDIOSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['PushAudioStreamResponse']
PushAudioRequest = _reflection.GeneratedProtocolMessageType('PushAudioRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHAUDIOREQUEST,
  '__module__' : 'sage.audio2face.proto.audio2face_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.audio2face.PushAudioRequest)
  })
_sym_db.RegisterMessage(PushAudioRequest)

PushAudioResponse = _reflection.GeneratedProtocolMessageType('PushAudioResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUSHAUDIORESPONSE,
  '__module__' : 'sage.audio2face.proto.audio2face_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.audio2face.PushAudioResponse)
  })
_sym_db.RegisterMessage(PushAudioResponse)

PushAudioStreamRequest = _reflection.GeneratedProtocolMessageType('PushAudioStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHAUDIOSTREAMREQUEST,
  '__module__' : 'sage.audio2face.proto.audio2face_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.audio2face.PushAudioStreamRequest)
  })
_sym_db.RegisterMessage(PushAudioStreamRequest)

PushAudioRequestStart = _reflection.GeneratedProtocolMessageType('PushAudioRequestStart', (_message.Message,), {
  'DESCRIPTOR' : _PUSHAUDIOREQUESTSTART,
  '__module__' : 'sage.audio2face.proto.audio2face_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.audio2face.PushAudioRequestStart)
  })
_sym_db.RegisterMessage(PushAudioRequestStart)

PushAudioStreamResponse = _reflection.GeneratedProtocolMessageType('PushAudioStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUSHAUDIOSTREAMRESPONSE,
  '__module__' : 'sage.audio2face.proto.audio2face_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.audio2face.PushAudioStreamResponse)
  })
_sym_db.RegisterMessage(PushAudioStreamResponse)

_AUDIO2FACE = DESCRIPTOR.services_by_name['Audio2Face']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUSHAUDIOREQUEST._serialized_start=61
  _PUSHAUDIOREQUEST._serialized_end=184
  _PUSHAUDIORESPONSE._serialized_start=186
  _PUSHAUDIORESPONSE._serialized_end=239
  _PUSHAUDIOSTREAMREQUEST._serialized_start=242
  _PUSHAUDIOSTREAMREQUEST._serialized_end=375
  _PUSHAUDIOREQUESTSTART._serialized_start=377
  _PUSHAUDIOREQUESTSTART._serialized_end=485
  _PUSHAUDIOSTREAMRESPONSE._serialized_start=487
  _PUSHAUDIOSTREAMRESPONSE._serialized_end=546
  _AUDIO2FACE._serialized_start=549
  _AUDIO2FACE._serialized_end=761
# @@protoc_insertion_point(module_scope)
